stages:
  - build_mr
  - build
  - deploy
  - notify
  - cleanup

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/kronfort-frontend:latest"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # Runs on main branch

build_mr:
  stage: build_mr
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE/kronfort-frontend" .
  allow_failure: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - export KUBECONFIG=/home/test-perimeter/.kube/config
    - kubectl config set-cluster minikube --server=https://$(minikube ip):8443 --insecure-skip-tls-verify=true
    - kubectl cluster-info
  script:
    - |
      sed -i "s#image: .*#image: $IMAGE_NAME#g" k8s/deployment.yml
      cat k8s/deployment.yml
      kubectl apply -f k8s/deployment.yml
      kubectl apply -f k8s/service.yml
      kubectl rollout restart deployment kronfort
  when: on_success
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

telegram_alert_failure:
  stage: notify
  script:
    - |
      curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
      -d "chat_id=$TELEGRAM_CHAT_ID" \
      -d "text=【 *Frontend* 】【 *Kronfort* 】%0A 🚨 *GitLab CI/CD Job FAILED* 🚨%0A🛑 Repo: *$CI_PROJECT_NAME*%0A📝 Commit: *$CI_COMMIT_MESSAGE*%0A📛 Job: *$CI_JOB_NAME*%0A📌 Status: *$CI_JOB_STATUS*%0A🔗 [View Pipeline]($CI_PIPELINE_URL)" \
      -d "parse_mode=Markdown"
  when: on_failure  # Runs only if a job fails
  only:
    - main

telegram_alert_success:
  stage: notify
  script:
    - |
      whoami
      curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendPhoto" \
      -F "chat_id=$TELEGRAM_CHAT_ID" \
      -F "caption=Project: *Frontend | Kronfort*%0A🚀 Repo: [$CI_PROJECT_NAME]($CI_PROJECT_URL)%0A📝 Commit: *$CI_COMMIT_MESSAGE*%0A💚 Status: *Pipeline Succeeded*%0A🔗 [View Pipeline]($CI_PIPELINE_URL)" \
      -F "parse_mode=Markdown"
      -F "photo=@/home/test-perimeter/devops-assets/kronfort-frontend/success.png"
  when: on_success  # Runs only if the pipeline is successful
  only:
    - main

telegram_alert_failure_slave:
  stage: notify
  script:
    - |
      curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
      -d "chat_id=$TELEGRAM_CHAT_ID" \
      -d "text=【 *Frontend* 】【 *Kronfort* 】%0A🚨 *GitLab CI/CD Job FAILED* 🚨%0A🛑 Repo: *$CI_PROJECT_NAME*%0A🔀 Merge Request: [!$CI_MERGE_REQUEST_ID]($CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_ID)%0A📝 Commit: *$CI_COMMIT_MESSAGE*%0A📌 Status: *$CI_JOB_STATUS*%0A🔗 [View Pipeline]($CI_PIPELINE_URL)" \
      -d "parse_mode=Markdown"
  when: on_failure  # Runs only if a job fails
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

telegram_alert_success_slave:
  stage: notify
  script:
    - |
      curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
      -d "chat_id=$TELEGRAM_CHAT_ID" \
      -d "text=【 *Frontend* 】【 *Kronfort* 】%0A✅ *GitLab CI/CD Pipeline SUCCESS* 🎉%0A🚀 Repo: *$CI_PROJECT_NAME*%0A🔀 Merge Request: [!$CI_MERGE_REQUEST_ID]($CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_ID)%0A📝 Commit: *$CI_COMMIT_MESSAGE*%0A💚 Status: *Pipeline Succeeded*%0A🔗 [View Pipeline]($CI_PIPELINE_URL)" \
      -d "parse_mode=Markdown"
  when: on_success  # Runs only if the pipeline is successful
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

cleanup_untagged_images:
  stage: cleanup
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker images --filter "dangling=true" -q | xargs -r docker rmi -f
  when: always  
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  
    - if: '$CI_COMMIT_BRANCH == "main"'
