export const transliterate = (text: string) => {
  const cyrillicToLatinMap: Record<string, string> = {
    а: 'a',
    б: 'b',
    в: 'v',
    г: 'g',
    д: 'd',
    е: 'e',
    ё: 'yo',
    ж: 'zh',
    з: 'z',
    и: 'i',
    й: 'y',
    к: 'k',
    л: 'l',
    м: 'm',
    н: 'n',
    о: 'o',
    п: 'p',
    р: 'r',
    с: 's',
    т: 't',
    у: 'u',
    ф: 'f',
    х: 'kh',
    ц: 'ts',
    ч: 'ch',
    ш: 'sh',
    щ: 'shch',
    ъ: '',
    ы: 'y',
    ь: '',
    э: 'e',
    ю: 'yu',
    я: 'ya',
    А: 'A',
    Б: 'B',
    В: 'V',
    Г: 'G',
    Д: 'D',
    Е: 'E',
    Ё: 'Yo',
    Ж: 'Zh',
    З: 'Z',
    И: 'I',
    Й: 'Y',
    К: 'K',
    Л: 'L',
    М: 'M',
    Н: 'N',
    О: 'O',
    П: 'P',
    Р: 'R',
    С: 'S',
    Т: 'T',
    У: 'U',
    Ф: 'F',
    Х: 'Kh',
    Ц: 'Ts',
    Ч: 'Ch',
    Ш: 'Sh',
    Щ: 'Shch',
    Ъ: '',
    Ы: 'Y',
    Ь: '',
    Э: 'E',
    Ю: 'Yu',
    Я: 'Ya'
  }

  return text
    .split('')
    .map((char) => cyrillicToLatinMap[char] || char)
    .join('')
    .toLowerCase()
}

export const reverseTransliterate = (text: string) => {
  const latinToCyrillicMap: Record<string, string> = {
    shch: 'щ',
    Shch: 'Щ',
    zh: 'ж',
    Zh: 'Ж',
    kh: 'х',
    Kh: 'Х',
    ts: 'ц',
    Ts: 'Ц',
    ch: 'ч',
    Ch: 'Ч',
    sh: 'ш',
    Sh: 'Ш',
    yo: 'ё',
    Yo: 'Ё',
    yu: 'ю',
    Yu: 'Ю',
    ya: 'я',
    Ya: 'Я',
    e: 'е',
    E: 'Е',
    э: 'э',
    Э: 'Э',
    a: 'а',
    A: 'А',
    b: 'б',
    B: 'Б',
    v: 'в',
    V: 'В',
    g: 'г',
    G: 'Г',
    d: 'д',
    D: 'Д',
    z: 'з',
    Z: 'З',
    i: 'и',
    I: 'И',
    y: 'ы',
    Y: 'Ы',
    й: 'й',
    Й: 'Й',
    k: 'к',
    K: 'К',
    l: 'л',
    L: 'Л',
    m: 'м',
    M: 'М',
    n: 'н',
    N: 'Н',
    o: 'о',
    O: 'О',
    p: 'п',
    P: 'П',
    r: 'р',
    R: 'Р',
    s: 'с',
    S: 'С',
    t: 'т',
    T: 'Т',
    u: 'у',
    U: 'У',
    f: 'ф',
    F: 'Ф'
  }

  const regex = new RegExp(
    Object.keys(latinToCyrillicMap)
      .sort((a, b) => b.length - a.length)
      .join('|'),
    'g'
  )

  return text.replace(regex, (matched) => latinToCyrillicMap[matched] || matched).toLowerCase()
}
